### ISSUE TITLE
igc beta version: pipeline failing at deploy stage

### ISSUE THREAD

**Issue by RamyaRaghuveera** [IBM/template-node-angular#12]
While testing beta toolkit on ocp44 cluster on VPC  with 0.5.10-beta.4 version of igc, pipeline is failing at deploy stage with the following error:
![image](https://user-images.githubusercontent.com/16119907/91041468-bf8fa380-e62d-11ea-9b8a-ebfc4ca760b2.png)

Pipeline is working fine with non-beta version of toolkit & igc. Webhook is working for the template
Have attached the deploy step logs for reference.
[logs.txt](https://github.com/IBM/template-node-angular/files/5117545/logs.txt)

**Comment by csantanapr** [comment]
You need to dig with `oc` or UI why is your deployment/template-node-angular not running correctly
