### ISSUE TITLE
Pipeline failing at health stage 

### ISSUE THREAD

**Issue by RamyaRaghuveera** [IBM/template-node-angular#8]
Issue:
The pipeline is failing at health stage:
<img width="1095" alt="AngularCodePatternError" src="https://user-images.githubusercontent.com/16119907/88286380-4808e480-cd0e-11ea-8143-62b30d7ea699.png">

Probable Cause:
 route.yaml is missing from chart/templates folder

**Comment by mjperrins** [comment]
We have removed Angular for now, until we can get a developer to focus on cleaning this up and actually make it involve to showing the 12 UI patterns.

**Comment by abalasu1** [comment]
I have fixed the angular starter kit, can you please merge pr.

**Comment by mjperrins** [comment]
Merged can you retest @RamyaRaghuveera

**Comment by RamyaRaghuveera** [comment]
Sure Matt.
 
Thanks & Regards,
Ramya Raghuveera
Senior Blockchain Specialist
E-mail: ramragh1@in.ibm.com
Contact: +918095197467
LinkedIn: https://www.linkedin.com/in/ramya-raghuveera-6a940866/ 
 
Be passionate , take risks and always follow your dreams
 
 
 
----- Original message -----From: Matthew Perrins <notifications@github.com>To: IBM/template-node-angular <template-node-angular@noreply.github.com>Cc: RamyaRaghuveera <ramragh1@in.ibm.com>, Mention <mention@noreply.github.com>Subject: [EXTERNAL] Re: [IBM/template-node-angular] Pipeline failing at health stage (#8)Date: Mon, Aug 3, 2020 5:22 PM 
 
Merged can you retest @RamyaRaghuveera

**Comment by RamyaRaghuveera** [comment]
Hi Matt,
 
I have tested the changes. Pipeline is working fine end-to-end now.
 
Thanks & Regards,
Ramya Raghuveera
Senior Blockchain Specialist
E-mail: ramragh1@in.ibm.com
Contact: +918095197467
LinkedIn: https://www.linkedin.com/in/ramya-raghuveera-6a940866/ 
 
Be passionate , take risks and always follow your dreams
 
 
 
----- Original message -----From: Ramya Raghuveera/India/IBMTo: reply@reply.github.comCc: mention@noreply.github.com, template-node-angular@noreply.github.comSubject: Re: [EXTERNAL] Re: [IBM/template-node-angular] Pipeline failing at health stage (#8)Date: Mon, Aug 3, 2020 7:03 PM 
Sure Matt.
 
Thanks & Regards,
Ramya Raghuveera
Senior Blockchain Specialist
E-mail: ramragh1@in.ibm.com
Contact: +918095197467
LinkedIn: https://www.linkedin.com/in/ramya-raghuveera-6a940866/ 
 
Be passionate , take risks and always follow your dreams
 
 
 
----- Original message -----From: Matthew Perrins <notifications@github.com>To: IBM/template-node-angular <template-node-angular@noreply.github.com>Cc: RamyaRaghuveera <ramragh1@in.ibm.com>, Mention <mention@noreply.github.com>Subject: [EXTERNAL] Re: [IBM/template-node-angular] Pipeline failing at health stage (#8)Date: Mon, Aug 3, 2020 5:22 PM 
 
Merged can you retest @RamyaRaghuveera

**Comment by RamyaRaghuveera** [comment]
Pipeline is working end-to-end with igc version 0.5.11
